apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: jenkins-operator
  namespace: openshift-marketplace
spec:
  displayName: Jenkins Operator
  image: registry-proxy.engineering.redhat.com/rh-osbs/iib:30198
  publisher: "Jenkins Community"
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 15m