
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backupworkers.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: BackupWorker
    listKind: BackupWorkerList
    plural: backupworkers
    singular: backupworker
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BackupWorker is the Schema for the backupworkers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BackupWorkerSpec defines the desired state of BackupWorker
          properties:
            foo:
              description: Foo is an example field of BackupWorker. Edit BackupWorker_types.go
                to remove/update
              type: string
          type: object
        status:
          description: BackupWorkerStatus defines the observed state of BackupWorker
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
